name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
          
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"
          git clone https://github.com/BananeRapeuse/iPwnStrap/ && cd iPwnStrap
          make package
