name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"
           make package
           
    - name: Upload
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
          host: eu-central-1.sftpcloud.io
          port: 22
          username: 8fd210395bda44b59934fa83aec3115c
          password: ChJ5FaC4SNzuefgdVlWB8DMgecDiA0al
          forceUpload: true
          dryRun: false
          localDir: '.packages/'
          remoteDir: '/artifacts/loader/universal_lite'
