name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build iPwnStrap 
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"
           make package

    - name: List files for debugging
      run: find / -name '*.tipa'

    - name: Upload the app
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
          host: eu-central-1.sftpcloud.io
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          forceUpload: true
          dryRun: false
          localDir: './.theos/packages/'
          remoteDir: '/.packages/'
